### ISSUE TITLE
Artifacts of the generated graph

### ISSUE THREAD

**Issue by Qi2013** [leebyron/streamgraph#2]
Hi leebyron,
There seems be some artifacts in the generated graph. Any idea to remove them? Thanks.

Best 
Qi
![ny2](https://f.cloud.github.com/assets/3496689/1420257/1b70b616-3fdd-11e3-9ecf-c7fb6b877e34.png)

**Comment by leebyron** [comment]
Unfortunately this is a bug in the way layers are drawn due to how they use Processing's curve drawing library. I'm not aware of an automated way to fix them, but opening and tweaking them in Illustrator or another vector editing tool can help.
