### ISSUE TITLE
Label Placement Algorithm?

### ISSUE THREAD

**Issue by curran** [leebyron/streamgraph#3]
I'm searching for implementations or descriptions of a label placement algorithm that maximizes text size and finds an optimal location for labels, similar to Figure 10 from the [original paper](http://leebyron.com/streamgraph/stackedgraphs_byron_wattenberg.pdf):

![image](https://user-images.githubusercontent.com/68416/28500330-20368140-6fe4-11e7-9aef-7038af456ab7.png)

Do you know of any resources for this? Thank you.

**Comment by leebyron** [comment]
A brute force technique was used for these labels, assuming a single line of text a size of the bounding box for text can be known, then a largest box of the same proportion is searched for within the labeled shape by looking at many possible locations and using the largest found, then the text is drawn in those coordinates

**Comment by curran** [comment]
Thanks for your response!

Do you know of any Open Source implementation available? I'm not able to track down the Listening History project code with the labeling, is it available?

There's still a lot to infer from your description. I think you're suggesting an algorithm like this to label a single area (StreamGraph layer):

 * Pick a starting font size.
 * Measure the bounding box of the label text.
 * Superimpose an M by N grid of possible (x, y) positions for the top left corner of the bounding box on the area, and test whether the bounding box fits within the area for each of those points.
 * If there is at least one grid point where the bounding box fits, increase the font size by a constant factor and go back to the first step.

There are a number of constants involved:

 * Initial font size
 * M and N (grid size for searching)
 * Factor by which to scale the font size on each iteration

There's also the problem of implementing the rectangle-in-polygon test (which may be simplified by the fact that the bounding lines are monotonic in X and nonintersecting).

Does this match with your description?

There could be an approach using randomness as well, rather than a grid. Another thought is that maybe simulated annealing could work.

I think there's a great opportunity here for introducing a new library. All of the StreamGraph examples with D3 don't have labels, except [this one](https://bl.ocks.org/veltman/14006cc042f5dff5a6e1ddf041afbae6) by @veltman, which implements a label position search for a fixed font size.
![image](https://user-images.githubusercontent.com/68416/28579558-a04c4a76-717a-11e7-89b7-b2115df8da31.png)
http://blockbuilder.org/search#text=streamgraph

I'd argue that the lack of an Open Source solution to StreamGraph label placement is the primary factor that's limiting mainstream adoption of the StreamGraph visualization technique.

**Comment by leebyron** [comment]
As far as I'm aware, there's no open source implementation of this labeling strategy. 

Your algorithm sounds like it will work, though I can think of a couple ways to speed it up:

First, the aspect ratio of a label will be the same regardless of font size, so rather than stepping through font sizes, just find the largest rectangle of the aspect ratio that fits and derive the font size from there. That also allows for setting some padding against the edges of the shape, or centering a label if you want a maximum label size. 

Second, rather than using a grid of starting points, just use points along the top edge of the shape, assuming a largest fitting rectangle would always have corners that touch the edges of the containing shape.

Those should reduce the search from N^3 points to N points

**Comment by curran** [comment]
Cheers! Fantastic ideas. Thank you so much for your suggestions.

I dug a little deeper and here's what I've found in terms of prior art:

 * [Chart.Streamgraph](https://tmroyal.github.io/Chart.Streamgraph/) ([repository](https://github.com/tmroyal/Chart.Streamgraph/)) has an [implementation of label placement](https://github.com/tmroyal/Chart.Streamgraph/blob/master/Chart.Streamgraph.js#L274), but it doesn't look like it finds the optimal placement (e.g. "Corn" here could be moved to the right).
![image](https://user-images.githubusercontent.com/68416/28589966-facee012-719d-11e7-8ead-9511e8db04ea.png)
 * [Streamgraph label positions bl.ock by Noah Veltman](https://bl.ocks.org/veltman/14006cc042f5dff5a6e1ddf041afbae6) Does a great job at label placement, but is single-scale only.
![image](https://user-images.githubusercontent.com/68416/28590058-63674542-719e-11e7-82a6-c3835eeeaac0.png)
 * [TechCrunch Analysis](http://www.neoformix.com/2008/TechCrunchAnalysis.html) by @Jeff-Clark implements StreamGraph label positioning, but unfortunately his code is not Open Source.
![image](https://user-images.githubusercontent.com/68416/28590116-9b031346-719e-11e7-869c-b8634b2ba001.png)

Will report back here if I get anything working.

**Comment by curran** [comment]
Greetings,

I've implemented a label placement algorithm and released it as a library.

https://github.com/curran/d3-area-label

It uses the [Bisection Method](https://en.wikipedia.org/wiki/Bisection_method) and [Linear Interpolation](https://en.wikipedia.org/wiki/Linear_interpolation) to search for the maximum label scale.

Here are some results using it:

[![image](https://user-images.githubusercontent.com/68416/28745722-a5d9e7a4-749b-11e7-92a8-227a56cd3ead.png)](https://bl.ocks.org/curran/2793201c7025c416c471e30d30546c6b)

[![image](https://user-images.githubusercontent.com/68416/28940637-0376ab84-78b3-11e7-858b-7b0320ea9e5a.png)](https://bl.ocks.org/curran/929c0cb58d5ec8dc1dceb7af20a33320)

It might be cool to add a link to this page http://leebyron.com/streamgraph/

**Comment by leebyron** [comment]
Nice work! If you add a small pull request to do so I'd be happy to take a look https://github.com/leebyron/streamgraph/tree/gh-pages

**Comment by curran** [comment]
@leebyron Thanks for welcoming the addition! I've submitted two PRs:

 * [Add d3-area-label link #4](https://github.com/leebyron/streamgraph/pull/4)
 * [Update d3.stack link #5](https://github.com/leebyron/streamgraph/pull/5) - Figured why not while I'm at it.
